### ISSUE TITLE
What is the policy for retiring a browser to "obsolete : very"?

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#861] opened 2016-08-03 19:16 UTC
There seems to be an excessive number of Firefox and Chrome versions active, which make the download bigger and the page slower.  What is the policy for retiring a browser with "obsolete : very"?

**Comment by claudepache** [comment] 2016-08-05 17:07
The usage of the only contributor caring about seems to be: "all but the last 10", see: https://github.com/kangax/compat-table/commit/4802cb08171ae4e50a660aa58c35bd10906f72e6, https://github.com/kangax/compat-table/commit/43f10efd69bff5405e1dec17930a24799ca5333f. That represents 13-14 months old, which, in my opinion, is not too much.

**Comment by afmenez** [comment] 2016-08-08 14:40
We currently have 14 Chrome and 10 Firefox obsolete versions (I removed 2 last week).  I believe this is too much.  Both browsers follow the rapid release with automatic updates policy, so older versions are not that important (as they are for IE for example, where we have only one obsolete version listed).

I suggest we keep the following:
- For Firefox keep 6 obsolete version, and at least one should be an ESR;
- For Chrome keep 6 obsolete versions;

This would remove 12 columns from the tables, making the much lighter.  Maybe even usable on mobile browsers.

**Comment by afmenez** [comment] 2016-08-09 18:45
Or we can go with browser usage.  If we retire browsers with less than 0.1% usage (according to http://caniuse.com), we get:
- Firefox ESR 38 + Firefox >=43;
- Chrome >= 42;
- IE >= 8;
- Safari >= 8;

Seems reasonable?

**Comment by claudepache** [comment] 2016-08-09 19:13
Not commenting about the idea of using browser usage, but about how you compute the threshold Firefox 43 / Chrome 42.

You say: Firefox N, for each N between 2 and 42 (excluding 38):  less than 0.1%, not significant.

I say: Firefox 2-42 (excluding 38):  0.02% + 0.04% + ... + 0.07% = 1.11%, significant.

Or, in other words, I am more interested into the _total_ number of users I leave behind.

**Comment by chicoxyzzy** [comment] 2016-09-20 22:04
Right now we have inconsistency between different tabs 😞

**Comment by ljharb** [comment] 2016-09-20 22:45
@chicoxyzzy let's make all of the tabs consistent ASAP - any browser that's not obsolete, or not "very" obsolete, in _any_ tab, should be not so in all of them.

**Comment by chicoxyzzy** [comment] 2016-09-20 23:13
@ljharb than we will end up rendering all browsers starting from IE 7, FF 2, Chrome 5, SF 3.2, etc. because they all will become at least obsolete.

Besides that I like idea of making all the things consistent. We can also merge all browsers definitions into one module. Two thing which really differs for all tabs are notes and some data for old browsers. Possible solutions for these two things respectively:
- move all notes data to browsers definitions module each tab's note to it's own field inside `notes` property
- mark unknown tests results as `unknown` with grey cell colour and a link to note describing how to contribute to the table

**Comment by afmenez** [comment] 2016-09-20 23:14
@ljharb, I am not sure we should do this for all the tabs.  If we do, the "ES5" and "non-standard" tabs will disappear with time, as all the columns tend to become very obsolete.

**Comment by afmenez** [comment] 2016-09-20 23:19
@chicoxyzzy, I already suggested having all browser definitions single place in #891, this would be great and solve the issue with my comment above since the supported versions will be on the "ES5" and "non-standard" tables.
I already tried to do this, but some browsers are only in certain modules. Your suggestion to mark unknown test results would solve that.

**Comment by ljharb** [comment] 2016-09-20 23:35
Hmm, that's a good point. Perhaps we should change "obsolete" to be the _date_ we began considering it obsolete, and each tab can have their own threshold for when something is "obsolete" as well as "very"? Or something similar?

**Comment by chicoxyzzy** [comment] 2016-10-06 23:56
Currently IE 9 and 10-11 are mark as stable in ES5 tab. In all other tabs only IE 11 is marked as stable

**Comment by afmenez** [comment] 2016-10-07 13:05
You are right @chicoxyzzy, IE9 and IE10 are indeed obsolete:
http://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/
They need to be marked on the INTL and NON-STANDARD tabs too.

**Comment by afmenez** [comment] 2016-10-11 13:08
This issue was about "obsolete: very" on Chrome and Firefox, and has no relation to PR #933.  I don't think it should be closed.

**Comment by chicoxyzzy** [comment] 2016-11-22 11:49
Just for history: https://github.com/kangax/compat-table/pull/966#issuecomment-262122273

**Comment by graingert** [comment] 2016-11-22 12:51
dupe of https://github.com/kangax/compat-table/issues/740

**Comment by chicoxyzzy** [comment] 2016-11-22 12:52
Yes lets keep discussion there

**Closed as completed by chicoxyzzy** 2016-11-22 12:52 UTC
Labels: maintenance
