### ISSUE TITLE
Feature to be able to select which browsers, engines, etc. you're interested in and get shown only all the available or unavailable features

### ISSUE THREAD

**Issue by LJNielsenDk** [compat-table/compat-table#799] opened 2016-05-20 09:58 UTC
This would be useful if you're only targeting say the x major browsers and the most recent y versions of them and want to easily know which subset of features you can use across all of them.

**Comment by chicoxyzzy** [comment] 2016-09-21 08:06
Dupe of #771

**Closed as completed by chicoxyzzy** 2016-09-21 08:06 UTC
