### ISSUE TITLE
Is raw data available?

### ISSUE THREAD

**Issue by opcodewriter** [compat-table/compat-table#785] opened 2016-04-28 06:49 UTC
Is raw data somehow available, by a REST API or just as a JSON file how caniuse.com does it: https://github.com/fyrd/caniuse

**Comment by sarahkadar** [comment] 2016-04-28 07:01
take a look at `data-[es5|es6|esnext|intl|non-standard].js`.

**Comment by chicoxyzzy** [comment] 2016-07-19 23:23
I think it's a good idea to have raw data in another repo or in separate json files. I'd like to make a web page that will show progress of features in ECMAScript process. I need some data which compat table already has. For example, I want to show that feature needs to be implemented in 2 browsers to move from stage 3 to stage 4 and in it's already available under flag in one of them. So at least two project will share same data and we can maintain it together.

**Comment by zoontek** [comment] 2016-08-24 09:57
+1 for putting raw data in another repo.
Babel could actually use this data in a customized preset using browserlist.
Discussion has started here: https://github.com/babel/babel/pull/3476

**Comment by chicoxyzzy** [comment] 2016-08-25 13:08
Babel announced that they

> ...also will be working on getting a target/env (autoprefixer) preset soon

https://babeljs.io/blog/2016/08/24/6.14.0

So yes. @kangax @webbedspace @zloirock @ljharb what do you think about creating something similar to https://github.com/fyrd/caniuse?

**Comment by ljharb** [comment] 2016-08-25 17:13
I think the first start would be moving the data to be in a consumable format within this repo - moving it into a separate repo and defining the API can come later.

**Comment by chicoxyzzy** [comment] 2016-09-21 08:10
previous discussion https://github.com/kangax/compat-table/issues/711

**Comment by chicoxyzzy** [comment] 2016-09-21 08:22
I like proposal from #711. We can have raw data and test suit separated.

**Comment by chicoxyzzy** [comment] 2016-09-21 10:17
Duplicate of #711. Let's discuss raw data there

**Closed as completed by chicoxyzzy** 2016-09-21 10:17 UTC
