### ISSUE TITLE
ES6 modules

### ISSUE THREAD

**Issue by silverwind** [compat-table/compat-table#501] opened 2015-04-15 14:33 UTC
These are part of the spec, can we add them?

From what I gathered, Babel seems to support them: https://babeljs.io/docs/learn-es6/#modules

**Comment by silverwind** [comment] 2015-04-15 22:23
Been trying to write a test for this, but it seems impossible as I get a uncatchable `SyntaxError` in `babel-node` when trying to wrap the `import`:

``` js
> try {import * as a from "b"} catch(e) {console.log(typeof e)};
SyntaxError: repl: 'import' and 'export' may only appear at the top level (1:5)
```

**Comment by zloirock** [comment] 2015-04-15 23:03
![script / module](https://pbs.twimg.com/media/CCkQC9hW4AI5coy.png:large)
`import` forbidden outside of modules. All `babel` output uses modules syntax. How do you propose test it within this table? I think, only manually check.

**Comment by kangax** [comment] 2015-04-15 23:05
Duplicate of #316

**Closed as completed by kangax** 2015-04-15 23:05 UTC

**Comment by silverwind** [comment] 2015-04-15 23:30
Whoops, sorry I missed that issue.

**Comment by silverwind** [comment] 2015-04-16 05:09
> How do you propose test it within this table?

I suppose one could inject a `<script type="module">` and inside of it, test for `self === undefined` in a browser. On the server, it seems impossible so far.
