### ISSUE TITLE
run 'npm install' error, the latest version

### ISSUE THREAD

**Issue by renmm** [compat-table/compat-table#803] opened 2016-05-25 08:08 UTC
My local environment：
- node v5.9.1
- npm  v3.7.3
- mac

console log:
- `Failed` at the `closurecompiler@1.5.3` install script 'npm run-script configure'.

---

detailed information（npm-debug.log）：

24707 error Darwin 14.4.0
24708 error argv "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.9.1/bin/node" "/usr/local/Cellar/nvm/0.29.0/versions/node/v5.9.1/bin/npm" "install"
24709 error node v5.9.1
24710 error npm  v3.7.3
24711 error code ELIFECYCLE
24712 error closurecompiler@1.5.3 install: `npm run-script configure`
24712 error Exit status 1
24713 error Failed at the closurecompiler@1.5.3 install script 'npm run-script configure'.
24713 error Make sure you have the latest version of node.js and npm installed.
24713 error If you do, this is most likely a problem with the closurecompiler package,
24713 error not with npm itself.
24713 error Tell the author that this fails on your system:
24713 error     npm run-script configure
24713 error You can get information on how to open an issue for this project with:
24713 error     npm bugs closurecompiler
24713 error Or if that isn't available, you can get their info via:
24713 error     npm owner ls closurecompiler
24713 error There is likely additional logging output above.
24714 verbose exit [ 1, true ]

**Comment by ljharb** [comment] 2016-05-25 08:40
This works for me on my Mac on node 6, 5, and 4 (aside from the fact that I don't have Java installed, but the install works). Do you have any other errors while running `npm install`?

**Comment by renmm** [comment] 2016-05-31 07:52
#I just have to try the install NPM, the newspaper is wrong:  

> closurecompiler@1.5.3 install /Users/renmaomin/work/github/compat-table/node_modules/closurecompiler
> npm run-script configure
> 
> closurecompiler@1.5.3 configure /Users/renmaomin/work/github/compat-table/node_modules/closurecompiler
> node scripts/configure.js

Configuring ClosureCompiler.js 1.5.3 ...

  Downloading http://dl.google.com/closure-compiler/compiler-latest.tar.gz ...
  | 0 / 5 mb
  | 1 / 5 mb
  | 2 / 5 mb
  | 3 / 5 mb
  | 4 / 5 mb
  | 5 / 5 mb
  ✔ Download complete: /Users/renmaomin/work/github/compat-table/node_modules/closurecompiler/compiler/compiler.tar.gz (5 mb)
Unpacking /Users/renmaomin/work/github/compat-table/node_modules/closurecompiler/compiler/compiler.tar.gz ...
  | compiler.jar
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unknown compression method
    at Zlib._handle.onerror (zlib.js:363:17)

---

Why is this error report? @ljharb

**Comment by ljharb** [comment] 2016-05-31 16:04
@renmm node 5 is up to 5.11.0 - perhaps 5.9 has a bug? Can you try upgrading to the latest node 5 and see if that fixes it?

**Comment by chicoxyzzy** [comment] 2016-09-20 21:21
Node 5 is not supported anymore however AFAIR it worked fine for me even on 5 and I have Java 1.8.0_102 installed. @renmm do you still have an issue?

**Comment by chicoxyzzy** [comment] 2016-10-04 21:04
@renmm I'll close this cause nobody can reproduce the issue. Feel free to reopen it if you think issue still exists

**Closed as completed by chicoxyzzy** 2016-10-04 21:04 UTC
