### ISSUE TITLE
Feature displaying incorrectly on es2016+ table

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#906] opened 2016-09-15 16:23 UTC
On the es2016+ table, the feature named 2016 "misc/Proxy, "enumerate" handler removed" has the following data:
    res: {
      firefox24: true,
      firefox25: false,
      firefox47: true,
      chrome50: true,
      safari10: true,
      safaritp: true,
      webkit: true,
    },

I believe this means that the feature is not working on Firefox 25 to Firefox 46, but it is showing as working for FF31 to FF46 on the generated HTML table.  Can this a bug on the code that builds the table?

**Comment by chicoxyzzy** [comment] 2016-09-16 18:51
Confirmed. Seems like it's due to Firefox 25 is marked as `very` obsolete, but I didn't checked yet

**Comment by chicoxyzzy** [comment] 2016-09-16 18:54
It could affect other tests too.

**Comment by afmenez** [comment] 2016-09-16 19:03
Makes sense, it seems the parser is ignoring the flags set for "obsolete: very" versions.  I tested it with other attributes on other files and got the same result.  If it is not happening now, may happen in the future, as more browsers are marked as "obsolete: very".

**Comment by chicoxyzzy** [comment] 2016-09-17 07:37
I'll provide a PR next week if nobody else will take this

**Comment by chicoxyzzy** [comment] 2016-09-19 14:10
Algorithm works fine for obsolete browsers. FF25 just wasn't in the browsers list. Fix is here #908

We can close this issue

**Closed as completed** 2016-09-19 15:34 UTC
