### ISSUE TITLE
Separate data-*.js and UI/build files

### ISSUE THREAD

**Issue by matAtWork** [compat-table/compat-table#746] opened 2016-02-22 12:40 UTC
I have a project where the underlying data from the compat-table would be great, but i don't need the UI at all. 

Any chance we could break these out into a separate repo or npm project?

**Comment by chicoxyzzy** [comment] 2016-10-04 21:01
dupe of https://github.com/kangax/compat-table/issues/785 and https://github.com/kangax/compat-table/issues/711

**Closed as completed by chicoxyzzy** 2016-10-04 21:01 UTC
