### ISSUE TITLE
INTL table missing the proposed features for ECMA402

### ISSUE THREAD

**Issue by afmenez** [compat-table/compat-table#930] opened 2016-10-06 16:25 UTC
We have a table showing proposals for future versions of ECMAscript, but we have nothing about the proposed features for the internationalization API:
https://github.com/tc39/ecma402

**Comment by afmenez** [comment] 2017-09-28 18:41
The table could also be split by version, like the ES2016+ tab.  I believe currently there are 3 specifications:
[ECMAScript Internationalization APIs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Specifications)

**Comment by chicoxyzzy** [comment] 2019-11-02 14:56
Duplicate of #467

**Closed as completed by chicoxyzzy** 2019-11-02 14:56 UTC
Labels: new test, INTL
