### ISSUE TITLE
Module test

### ISSUE THREAD

**Issue by jblanche** [compat-table/compat-table#13] opened 2012-03-06 19:04 UTC
The module test looks wrong, it's the same as the rest parameters test.

**Comment by paulmillr** [comment] 2012-03-06 19:12
could you provide more details? how should it look?

**Comment by kangax** [comment] 2012-03-06 19:17
Actually yes, it was a duplicate of rest parameters one. Fixed to test for `module foo { }` not being an (syntax) error.

**Closed as completed by kangax** 2012-03-06 19:17 UTC
